**Importation de Données**

In [1]:
import pandas as pd
from IPython.display import display

df = pd.read_csv("sap_co_budget_reel_raw.csv")

display(df.head(10))

,Mois,Business_Unit_Code,Business_Unit,Centre_Cout_Code,Centre_Cout,Nature_Depense,Budget_EUR,Reel_EUR
0,2025-01,BU01,Construction France,CC1001,IT,Logiciels,6335.71,7373.09
1,2025-01,BU01,Construction France,CC1001,IT,Prestations externes,10702.77,11211.76
2,2025-01,BU01,Construction France,CC1001,IT,Salaires,15185.00,13688.95
3,2025-01,BU01,Construction France,CC1001,IT,Matériel,5493.95,6240.24
4,2025-01,BU01,Construction France,CC1001,IT,Déplacements,3887.34,4212.57
5,2025-01,BU01,Construction France,CC1001,IT,Logiciel,4574.10,5352.02
6,2025-01,BU01,Construction France,CC1002,Ressources Humaines,Logiciels,8121.53,7472.39
7,2025-01,BU01,Construction France,CC1002,Ressources Humaines,Prestations externes,7731.85,7040.04
8,2025-01,BU01,Construction France,CC1002,Ressources Humaines,Salaires,16785.82,17174.74
9,2025-01,BU01,Construction France,CC1002,Ressources Humaines,Matériel,7064.17,6683.45

**Audit**

In [2]:
# Valeurs manquantes

display(df.isnull().sum())

Mois                  0
Business_Unit_Code    0
Business_Unit         0
Centre_Cout_Code      0
Centre_Cout           0
Nature_Depense        0
Budget_EUR            1
Reel_EUR              0
dtype: int64

In [3]:
ligne_manquantes = df[df.isnull().any(axis=1)]

display(ligne_manquantes)

,Mois,Business_Unit_Code,Business_Unit,Centre_Cout_Code,Centre_Cout,Nature_Depense,Budget_EUR,Reel_EUR
29,2025-01,BU02,Construction UK,CC2002,Ressources Humaines,Énergie,NaN,4463.99

In [10]:
# Doublons
display(df.duplicated().sum())

np.int64(0)

In [12]:
#Format de donnée
display(df["Mois"].dtype)
display(df["Mois"].unique())

dtype('O')

array(['2025-01', '2025-02', '2025/08', '2025-03', '2025-04', '2025-05',
       '2025-06', '2025-07', '2025-08', '2025-09', '2025-10', '2025-11',
       '2025-12'], dtype=object)

In [16]:
#Coherence des libelle

display(df["Business_Unit_Code"].unique())
display(df["Business_Unit"].unique())
display(df["Centre_Cout_Code"].unique())
display(df["Centre_Cout"].unique())
display(df["Budget_EUR"].unique())
display(df["Reel_EUR"].unique())
display(df["Nature_Depense"].unique())

array(['BU01', 'BU02', 'BU03', 'BU04'], dtype=object)

array(['Construction France', 'Construction France ', 'Construction UK',
       'Energie', 'Infrastructures'], dtype=object)

array(['CC1001', 'CC1002', 'CC1003', 'CC2001', 'CC2002', 'CC2003',
       'CC3001', 'CC3002', 'CC3003', 'CC4001', 'CC4002', 'CC4003'],
      dtype=object)

array(['IT', 'Ressources Humaines', 'Finance', 'Maintenance', 'IT '],
      dtype=object)

array([  6335.71,  10702.77,  15185.  ,   5493.95,   3887.34,   4574.1 ,
         8121.53,   7731.85,  16785.82,   7064.17,   3909.89,   5551.72,
         6653.67,   7828.24,  19898.08,   7801.69,   2761.61,   7976.28,
         6062.99,  10444.86,  14818.01,   5394.43,   3168.44,   5622.16,
         7007.17,  11985.76,  23646.59,   7761.18,   2810.83,       nan,
         6390.84,  11225.18,  16534.09,   5841.88,   2781.56,   7280.08,
         4896.54,  10567.03,  21829.72,   6755.56,   4437.52,   5691.23,
         6087.83,  10689.87,  23081.9 ,   5752.3 ,   4222.65,   7275.48,
         6913.66,   6887.26,  13839.44,   6570.3 ,   4530.89,   5977.38,
         5767.31,   8314.66,  23540.73,   7910.3 ,   4312.71,   7713.21,
         8024.02,   8467.22,  15961.7 ,   8685.66,   2639.6 ,   6002.68,
         5342.47,  11841.71,  19102.94,   6777.24,   4646.14,   6290.09,
         5985.88,  10041.65,  14055.97,   9064.72,   2929.28,   8048.34,
         7496.33,   8033.24,  17472.06,   7910.82,   2814.61,   5654.81,
         5034.02,  10408.85,  19030.61,   7959.73,   4075.97,   7872.23,
         6205.16,  11743.35,  16285.77,   8682.33,   3737.27,   4835.17,
         8386.63,   8580.76,  21340.32,   8975.76,   3973.27,   5081.86,
         7240.07,   7297.95,  13554.67,   7554.68,   3994.12,   7063.85,
         6144.06,  10258.02,  20602.22,   5643.43,   3181.92,   8002.84,
         8353.98,  11041.98,  19730.56,   6070.02,   3214.62,   6823.7 ,
         8542.79,  11690.27,  13666.93,   7048.37,   4648.6 ,   5560.02,
         8194.43,   7665.26,  23610.47,   7644.26,   3916.52,   5004.3 ,
         8296.75,  10513.89,  17382.5 ,   8649.32,   4445.85,   6340.83,
         7988.35,  10540.62,  23112.06,   6827.45,   3839.39,   6176.15,
         5992.51,   6914.7 ,  22384.09,   5783.65,   4241.99,   6742.41,
         5076.56,   9669.43,  21341.79,   7418.46,   4294.89,   6080.3 ,
         4973.87,  11264.29,  17916.69,   5907.04,   3778.38,   6876.71,
         8598.97,   9743.51,  18031.68,   6745.09,   2655.23,   4665.61,
         8211.3 ,   9310.54,  18809.45,   5977.45,   3461.86,   6786.34,
         6335.99,   9466.94,  20613.89,   5546.39,   2680.67,   7884.83,
         6388.86,   9224.57,  23667.82,   9287.  ,   3036.16,   4862.8 ,
         5243.33,   7134.42,  22624.65,   8670.77,   2873.15,   6764.19,
         7741.78,   8272.99,  21606.64,   9410.12,   3406.24,   5726.89,
         8222.81,  10804.7 ,  14613.74,   7372.06,   3297.1 ,   5901.13,
         8405.99,   8474.29,  23766.56,   7903.72,   3240.74,   6921.07,
         7962.16,   7242.51,  14121.63,   7104.43,   3361.92,   5014.77,
         7286.05,   7204.18,  14285.84,   8216.22,   2803.16,   5847.37,
         8044.92,  12074.41,  17563.6 ,   8514.02,   3515.87,   4900.31,
         4919.28,   7054.04,  14769.28,   8383.39,   4645.56,   5528.56,
         5747.02,   6815.63,  13966.13,   7466.34,   2779.97,   7989.49,
         7329.65,   9204.52,  19810.59,   5440.87,   4620.86,   6140.36,
         5956.79,   9253.97,  19803.49,   9342.46,   4091.14,   5614.3 ,
         7545.45,  11669.01,  23757.84,   7826.34,   4583.73,   4662.79,
         6343.21,  12081.29,  19916.61,   9323.64,   4385.49,   5993.35,
         5094.86,  11139.67,  24263.68,   8479.75,   4409.26,   6121.96,
         8595.8 ,   7984.67,  20175.78,   5726.94,   3717.65,   6372.59,
         7027.44,  11483.93,  14947.36,   8421.58,   4103.57,   4990.94,
         6242.29,   8868.12,  23264.91,   7408.76,   3457.74,   7604.51,
         5448.59,   9407.43,  18458.67,   7319.  ,   3955.14,   4773.11,
         5374.38,   7499.67,  15464.3 ,   9016.51,   4026.87,   5192.24,
         5533.85,   7705.86,  14802.87,   6116.6 ,   3682.18,   4641.52,
         7323.81,  11467.32,  14159.64,   8636.05,   3012.49,   5833.7 ,
         7286.19,   9247.69,  13896.18,   8246.07,   3699.52,   4885.82,
         6952.21,   8203.91,  13716.77,   6138.08,   2876.5 ,   6636.93,
         7952.77,   7219.37,  19837.88,   7062.97,   3220.93,   6825.3 ,
         6263.78,  10021.18,  14599.25,   6283.02,   3016.79,   5124.14,
         5187.91,   8966.14,  14710.02,   9321.78,   4340.85,   5115.2 ,
         8499.57,   9836.71,  21810.52,   6609.45,   3690.98,   4913.41,
         6000.66,   7583.56,  19251.97,   6663.74,   2758.09,   5660.47,
         5868.1 ,  10855.23,  18593.02,   6715.25,   4369.3 ,   4947.47,
         8534.53,   7109.08,  19704.31,   5837.04,   3048.42,   5091.36,
         7469.27,   8687.68,  17738.41,   7094.37,   3596.63,   7191.39,
         5780.63,   8823.01,  23289.9 ,   5740.97,   3943.19,   5001.38,
         7293.28,  11577.02,  15138.09,   6293.65,   2695.42,   7244.85,
         6209.12,   7347.41,  14876.88,   8598.64,   3106.43,   7092.13,
         7581.4 ,   8109.71,  15461.26,   7700.25,   3595.21,   5052.07,
         6847.97,   6847.79,  23566.88,   8175.93,   4110.2 ,   6574.64,
         6529.11,  11795.58,  18369.07,   9386.33,   2886.79,   7631.63,
         7180.97,   7045.71,  22170.82,   6650.7 ,   3753.53,   5746.85,
         7751.25,   7962.87,  15021.26,   7343.14,   4546.18,   6590.12,
         4926.07,   7711.39,  15105.56,   5608.47,   3679.61,   4741.48,
         5693.63,   7857.75,  13894.74,   7622.33,   4253.61,   6387.8 ,
         6437.98,   7588.3 ,  22807.28,   6817.9 ,   3977.4 ,   4591.39,
         7667.29,   6896.32,  15995.61,   5332.78,   4304.82,   6849.89,
         5262.82,  10650.24,  22466.37,   8055.96,   3240.61,   4546.81,
         5685.76,   7729.75,  18051.39,   8683.26,   3169.79,   6625.06,
         7309.18,   9731.05,  16680.23,   8457.14,   4448.78,   7720.39,
         6533.33,   8200.86,  20341.56,   5835.3 ,   4692.24,   5118.05,
         4946.72,   7385.86,  16459.8 ,   7985.97,   3058.48,   4992.79,
         8283.17,   9992.79,  15394.01,   7008.84,   3714.73,   5098.62,
         5197.91,   8074.89,  16617.89,   8269.99,   3814.45,   6889.22,
         7732.03,   6918.39,  19926.84,   7334.74,   3326.91,   4883.75,
         7714.94,  10467.37,  16161.14,   8607.55,   3196.5 ,   5799.51,
         8452.52,  11881.28,  15499.44,   8916.37,   4318.78,   6992.2 ,
         5848.71,   7944.53,  23695.84,   8213.42,   3004.21,   7795.76,
         7594.94,  11741.74,  23698.08,   8870.58,   3295.11,   4633.23,
         5772.03,   7165.55,  17170.65,   5524.5 ,   3757.93,   5647.51,
         8330.31,   8007.98,  22897.07,   8923.75,   4597.04,   8092.56,
         7867.03,   9341.33,  22935.71,   8476.75,   3509.85,   5359.6 ,
         6258.03,   8350.06,  13954.61,   9398.43,   3432.09,   5285.71,
         7941.75,   9004.94,  23703.11,   7826.33,   4706.45,   7893.83,
         7245.17,   7995.62,  15881.25,   8524.25,   2746.47,   7681.63,
         8755.14,   8889.71,  21017.02,   8676.5 ,   3095.02,   6634.58,
         5231.8 ,   8184.24,  23098.48,   8870.94,   4001.01,   4813.15,
         6328.49,  10656.47,  14375.3 ,   8119.69,   4412.53,   6230.11,
         8091.26,  10411.29,  16383.91,   8599.19,   4411.22,   7050.11,
         7595.14,  10090.5 ,  15212.94,   8911.74,   4359.22,   5706.43,
         5501.96,  11243.52,  13568.97,   7841.09,   3951.81,   6782.42,
         7916.4 ,  10859.55,  23900.31,   7907.01,   2840.27,   6976.39,
         6048.76,   7113.69,  17235.54,   5442.12,   4669.33,   7198.75,
         7832.23,   6869.47,  18777.35,   8119.84,   3199.62,   6034.25,
         5513.13,  10495.88,  14389.72,   7998.95,   4621.81,   6056.41,
         6511.94,   8897.01,  24126.96,   9005.22,   3072.52,   6846.  ,
         8246.  ,  11978.24,  22881.13,   8487.87,   4223.15,   4972.48,
         8466.31,  11051.3 ,  14766.93,   8129.37,   3046.1 ,   4731.15,
         5924.07,   8425.95,  13625.5 ,   6898.47,   3885.04,   7001.93,
         7916.42,   9344.74,  16114.09,   5848.48,   3923.13,   6514.74,
         6148.2 ,   7224.48,  13858.59,   6917.08,   3816.84,   7382.11,
         5528.18,  10186.72,  13841.13,   5468.28,   4114.03,   7070.71,
         6198.86,   7182.62,  19414.  ,   7149.74,   3730.45,   4793.87,
         5838.7 ,  11457.63,  24039.34,   6014.9 ,   4008.29,   6499.31,
         5765.97,  12013.88,  15655.06,   5553.23,   3166.13,   7625.78,
         7771.56,   8618.05,  24166.62,   8891.53,   3546.09,   6252.01,
         8387.74,   8244.87,  23353.52,   7866.46,   4164.54,   7076.97,
         5575.76,  11995.53,  22727.36,   6288.37,   3560.14,   5793.24,
         5512.74,  11984.83,  20592.76,   8498.59,   4661.62,   5349.78,
         5537.06,   8569.82,  18153.59,   7842.01,   2975.79,   4632.02,
         7463.84,  11308.52,  19821.83,   6114.53,   3191.47,   6412.21,
         5028.44,   9191.87,  16914.49,   5424.61,   4696.92, 150000.  ,
         7367.57,   9205.6 ,  18779.54,   5836.54,   3271.65,   5226.67,
         8657.66,  10382.05,  22875.94,   8159.03,   4608.69,   6289.83,
         8263.73,   6914.09,  20946.89,   6155.84,   3452.12,   4883.73,
         8772.71,  12026.74,  22904.14,   7631.47,   4469.88,   5677.32,
         8025.6 ,  11058.19,  22332.61,   7536.85,   3306.63,   5926.22,
         6390.38,   8032.74,  15954.51,   7784.48,   3925.93,   5867.23,
         6899.42,   6888.47,  17606.11,   7686.72,   3901.6 ,   7426.75,
         8601.54,   7807.2 ,  20492.73,   6272.63,   2751.56,   5765.84,
         6769.9 ,   8288.31,  22172.68,   6557.49,   4128.92,   5988.78,
         5581.48,   7729.77,  21157.7 ,   7632.71,   4647.15,   7401.57,
         5044.31,  11887.58,  22347.24,   6207.94,   3908.06,   7523.5 ,
         6253.34,  10964.84,  22384.23,   8053.71,   3935.1 ,   6611.79,
         7748.81,   7920.39,  13755.3 ,   7799.79,   3112.09,   6640.11,
         8727.36,  10503.78,  18124.56,   8158.23,   2894.63,   7107.62,
         5944.23,   7212.55,  15572.17,   6201.96,   2770.79,   4743.41,
         5786.48,  11502.43,  19255.94,   6648.61,   4712.69,   6508.02,
         6689.3 ,   9786.4 ,  15393.27,   6093.92,   2828.02,   7222.19,
         7468.16,  11756.76,  17812.61,   9418.43,   3758.91,   6375.45,
         5222.59,   7439.65,  21945.9 ,   5401.87,   3177.54,   4815.51,
         7034.83,   8893.7 ,  19986.42,   9111.45,   4708.53,   5250.64,
         5328.83,   8805.37,  22875.01,   8568.13,   2794.93,   5124.69,
         6224.79,  10211.25,  14931.27,   9125.58,   3898.13,   5129.42,
         6429.79,   8734.69,  13778.77,   9295.08,   4653.23,   5622.54,
         6589.1 ,  10210.46,  20191.55,   5888.5 ,   4264.6 ,   4709.39,
         5100.34,  12061.87,  15036.29,   6523.76,   4078.54,   6333.92])

array([  7373.09  ,  11211.76  ,  13688.95  ,   6240.24  ,   4212.57  ,
         5352.02  ,   7472.39  ,   7040.04  ,  17174.74  ,   6683.45  ,
         3503.39  ,   5390.16  ,   7379.64  ,   7982.43  ,  17218.38  ,
         7070.46  ,   3212.12  ,   8907.67  ,   5348.97  ,  10395.25  ,
        15016.7   ,   6204.01  ,   3385.9   ,   5743.72  ,   6383.55  ,
        13253.78  ,  27082.27  ,   8958.1   ,   2571.    ,   4463.99  ,
         6004.48  ,  10862.93  ,  17015.06  ,   6512.09  ,   3270.2   ,
         6665.47  ,   5479.72  ,  11524.11  ,  19088.67  ,   6000.53  ,
         4684.64  ,   4956.92  ,   5827.94  ,  11335.48  ,  23216.49  ,
         6243.37  ,   4371.38  ,   -500.    ,   6852.05  ,   6099.39  ,
        14670.01  ,   6687.43  ,   4224.    ,   6571.12  ,   5048.73  ,
         7509.82  ,  26287.46  ,   8998.61  ,   3931.33  ,   7929.05  ,
         9193.2   ,   7504.64  ,  15817.18  ,   9849.9   ,   2688.56  ,
         5542.25  ,   5136.32  ,  11328.46  ,  20669.31  ,   7934.04  ,
         4335.26  ,   5971.12  ,   5160.86  ,  10201.15  ,  13240.07  ,
         8421.62  ,   2963.02  ,   7483.98  ,   8255.97  ,   8758.74  ,
        18496.98  ,   8122.88  ,   3168.26  ,   5154.65  ,   5260.53  ,
         8904.5   ,  17598.43  ,   7223.78  ,   3984.76  ,   7048.65  ,
         5506.74  ,  13381.8   ,  17389.86  ,   8970.73  ,   3474.95  ,
         5541.5   ,   8880.8   ,   8282.49  ,  19633.0944,   9939.39  ,
         3487.6   ,   5826.47  ,   6176.04  ,   7801.18  ,  12240.77  ,
         8146.41  ,   3690.6   ,   6557.31  ,   6735.99  ,  11594.06  ,
        21375.66  ,   5481.73  ,   2960.83  ,   7840.56  ,   8840.82  ,
        11217.22  ,  19977.8   ,   6606.67  ,   2758.22  ,   6198.97  ,
         9950.61  ,  11364.72  ,  15803.69  ,   8239.52  ,   5259.86  ,
         5432.59  ,   7822.28  ,   7923.92  ,  25491.99  ,   6742.76  ,
         4608.63  ,   5109.64  ,   9080.41  ,  11374.13  ,  16459.24  ,
         9664.21  ,   5118.82  ,   6439.12  ,   8503.5   ,  11727.62  ,
        22223.13  ,   6015.08  ,   3309.02  ,   6355.71  ,   6262.02  ,
         5962.72  ,  21687.11  ,   5912.86  ,   3907.81  ,   5920.94  ,
         5205.23  ,  10253.    ,  25013.24  ,   7096.32  ,   4034.51  ,
         5325.68  ,   5807.86  ,  12161.74  ,  16253.79  ,   5508.78  ,
         4102.62  ,   6480.46  ,   9403.03  ,  10248.89  ,  16801.04  ,
         7420.2   ,   2358.65  ,   4028.48  ,   8886.32  ,   8214.55  ,
        18926.93  ,   5936.63  ,   3646.14  ,   5869.84  ,   6694.19  ,
        10722.65  ,  18630.18  ,   5890.26  ,   2796.76  ,   8199.48  ,
         6786.79  ,  11807.4496,  23133.26  ,  10668.59  ,   2650.23  ,
         4162.62  ,   5638.63  ,   6815.24  ,  19404.71  ,   8176.64  ,
         3102.78  ,   7708.24  ,   8633.23  ,   7516.46  ,  24118.53  ,
         9279.92  ,   3768.04  ,   6626.87  ,   8153.48  ,  11874.36  ,
        16774.27  ,   8276.84  ,   3776.91  ,   5037.06  ,   7398.32  ,
         9860.01  ,  24699.03  ,   7887.81  ,   3106.12  ,   7601.29  ,
         8842.57  ,   7337.82  ,  14564.27  ,   8119.95  ,   2987.51  ,
         5522.76  ,   6436.28  ,   7790.02  ,  16017.48  ,   7204.35  ,
         3295.37  ,   5685.47  ,   9352.96  ,  13265.12  ,  15413.03  ,
         8805.82  ,   4040.07  ,   4961.89  ,   4942.19  ,   6272.52  ,
        15718.05  ,   8739.78  ,   4523.42  ,   6283.97  ,   6711.74  ,
         7974.7   ,  15978.33  ,   8792.95  ,   2871.08  ,   8170.23  ,
         7913.07  ,   9730.05  ,  22730.32  ,   5129.21  ,   5285.28  ,
         6475.9   ,   5433.07  ,   8944.95  ,  17340.97  ,  10981.59  ,
         4201.24  ,   6279.89  ,   6818.55  ,  13086.06  ,  25883.87  ,
         7732.59  ,   5206.21  ,   4003.94  ,   7088.42  ,  10868.78  ,
        19432.52  ,  10516.13  ,   4405.97  ,   5635.09  ,   5784.5   ,
        13143.77  ,  25071.48  ,   9851.54  ,   4107.78  ,   5464.6   ,
         9025.91  ,   8556.86  ,  19534.07  ,   6137.1   ,   4107.5   ,
         7208.8   ,   7274.17  ,  11290.42  ,  12847.23  ,   8882.25  ,
         3776.42  ,   4266.25  ,   6521.15  ,   8818.16  ,  22448.88  ,
         8213.39  ,   3648.91  ,   8846.64  ,  20448.59  ,   8798.02  ,
        21659.6   ,   7015.17  ,   3675.31  ,   4260.14  ,   4837.63  ,
         7960.81  ,  14908.68  ,   9074.28  ,   3651.83  ,   4483.43  ,
         5212.52  ,   6775.54  ,  14833.32  ,   5934.38  ,   3968.76  ,
         5169.75  ,   6422.84  ,  13232.01  ,  13329.46  ,   9473.1   ,
         2768.74  ,   5891.41  ,   7080.3   ,  10141.62  ,  12969.36  ,
         9445.2   ,   3794.22  ,   4874.32  ,   6465.66  ,   7994.74  ,
        13117.16  ,   5880.74  ,   3290.35  ,   7128.75  ,   8067.97  ,
         7416.06  ,  21742.22  ,   6300.89  ,   3123.71  ,   7087.1   ,
         7363.38  ,   9302.51  ,  13145.8   ,   5673.73  ,   2848.1   ,
         5871.92  ,   5307.69  ,  10527.91  ,  14434.83  ,  10585.97  ,
         4059.16  ,   5476.6   ,   8786.27  ,   9270.05  ,  19885.19  ,
         6545.96  ,   3432.6   ,   5166.48  ,   6251.54  ,   7650.11  ,
        16693.41  ,   5959.76  ,   3245.41  ,   6324.21  ,   6307.6   ,
        11360.66  ,  18331.    ,   7767.83  ,   5105.35  ,   5398.61  ,
         7764.77  ,   7781.38  ,  22222.59  ,   6493.35  ,   2755.79  ,
         5696.26  ,   7638.16  ,   9899.41  ,  19857.75  ,   6912.69  ,
         3414.83  ,   7305.72  ,   6629.57  ,   9082.17  ,  24594.1   ,
         6660.36  ,   3787.51  ,   5561.68  ,   7483.22  ,  12853.24  ,
        14424.6   ,   6894.71  ,   2798.02  ,   8254.3   ,   6960.51  ,
         8297.65  ,  14595.78  ,   7734.24  ,   3380.86  ,   7528.86  ,
         7802.01  ,   7818.41  ,  17777.18  ,   7563.8   ,   4179.81  ,
         5271.61  ,   7202.55  ,   8765.1712,  24426.93  ,   9438.5   ,
         3700.57  ,   6904.79  ,   7136.49  ,  13629.06  ,  16300.13  ,
        10576.86  ,   3331.    ,   7793.54  ,   7049.35  ,   6768.22  ,
        18879.08  ,   6526.96  ,   4329.89  ,   5542.8   ,   7745.3   ,
         7957.33  ,  13642.42  ,   7256.83  ,   4407.93  ,   6976.61  ,
         5265.81  ,   9000.38  ,  14906.56  ,   6612.21  ,   3850.63  ,
         5203.71  ,   6526.94  ,   7173.56  ,  13975.08  ,   6644.26  ,
         4251.84  ,   6358.75  ,   6661.25  ,   6905.63  ,  26507.04  ,
         6404.36  ,   3917.27  ,   4139.28  ,   8184.41  ,   6367.03  ,
        17142.89  ,   4716.08  ,   3912.74  ,   6360.81  ,   4895.72  ,
        12060.12  ,  22041.1   ,   7392.51  ,   3713.06  ,   3993.09  ,
         4882.68  ,   8057.52  ,  20661.28  ,   8360.24  ,   3091.49  ,
         6217.36  ,   7200.32  ,   9671.91  ,  19398.93  ,   7579.61  ,
         4497.06  ,   8600.14  ,   5601.78  ,   8436.54  ,  19021.46  ,
         6567.78  ,   4802.41  ,   4810.25  ,   5697.23  ,   7683.14  ,
        17000.97  ,   8974.75  ,   2610.81  ,   5726.76  ,   8673.69  ,
        10686.91  ,  17730.14  ,   6843.68  ,   3215.09  ,   5575.6   ,
         5452.82  ,   7901.01  ,  16075.68  ,   7840.37  ,   3841.52  ,
         7985.66  ,   7120.66  ,   6479.4   ,  17275.98  ,   7679.16  ,
         3674.25  ,   4272.29  ,   7819.18  ,  10399.26  ,  18105.39  ,
         9289.69  ,   3339.63  ,   5104.85  ,   7566.28  ,  11847.8   ,
        15946.24  ,   9733.42  ,   4609.86  ,   7902.82  ,   5916.03  ,
         9342.22  ,  20449.77  ,   9489.22  ,   3116.63  ,   6713.72  ,
         7200.95  ,  13743.11  ,  23851.89  ,  10012.23  ,   3702.2   ,
         4849.92  ,   5135.88  ,   7737.18  ,  18701.81  ,   5270.62  ,
         4174.83  ,   5966.84  ,   8773.78  ,   6871.27  ,  19623.22  ,
         9142.82  ,   5119.26  ,   7815.27  ,   7730.44  ,   9874.5   ,
        21100.8532,   8373.87  ,   3837.68  ,   4751.05  ,   5912.51  ,
         7741.27  ,  11943.73  ,   9315.4   ,   3687.03  ,   6149.86  ,
         6984.81  ,  10266.61  ,  23803.67  ,   7083.78  ,   4360.3   ,
         8402.07  ,   7384.19  ,   7262.05  ,  14476.15  ,   8230.52  ,
         3212.83  ,   8881.18  ,   7944.29  ,   9780.62  ,  18931.83  ,
         8017.65  ,   3179.21  ,   6909.44  ,   5961.96  ,   7306.4   ,
        26918.16  ,   9910.08  ,   4128.17  ,   4739.94  ,   5921.68  ,
        10801.81  ,  13263.52  ,   7105.73  ,   4471.66  ,   6513.55  ,
         7806.26  ,  10793.29  ,  18676.8   ,   9177.82  ,   5012.06  ,
         7939.93  ,   8160.57  ,  11083.37  ,  17353.2   ,   7660.99  ,
         3890.72  ,   6250.58  ,   6161.81  ,  11439.89  ,  12818.91  ,
         9203.81  ,   3697.85  ,   6973.65  ,   7008.41  ,  11170.33  ,
        23011.65  ,   9152.91  ,   3292.68  ,   6086.11  ,   6555.02  ,
         7413.3   ,  18181.8   ,   6190.99  ,   5461.85  ,   6427.97  ,
         6720.94  ,   6572.65  ,  20734.59  ,   8096.68  ,   3772.51  ,
         6027.96  ,   6132.19  ,   9686.17  ,  15462.68  ,   7520.42  ,
         4158.93  ,   7033.87  ,   6907.3   ,  11388.1728,  23766.99  ,
         8337.8   ,   2643.21  ,   6651.67  ,   8296.79  ,  10914.86  ,
        25312.87  ,   9580.93  ,   4462.4   ,   4279.98  ,   8919.21  ,
        11149.68  ,  13161.93  ,   8064.35  ,   3083.34  ,   4930.1   ,
         6594.65  ,   8427.83  ,  11907.43  ,   6956.28  ,   3676.22  ,
         7939.08  ,   6832.46  ,   8266.61  ,  18943.7   ,   5934.06  ,
         4244.09  ,   5558.53  ,   6276.36  ,   6976.73  ,  12139.17  ,
         6182.46  ,   4112.73  ,   6762.38  ,   4889.72  ,  11033.62  ,
        16041.18  ,   5624.82  ,   4679.38  ,   7880.81  ,   6935.85  ,
         8226.18  ,  21738.01  ,   7595.74  ,   4071.5   ,   4170.26  ,
         5270.3   ,  10567.84  ,  23106.03  ,   6680.15  ,   4066.02  ,
         7066.94  ,   6796.87  ,  12790.07  ,  16820.97  ,   4776.42  ,
         3174.57  ,   8311.84  ,   7697.05  ,   8380.56  ,  20861.49  ,
         9255.76  ,   3862.88  ,   7116.22  ,   8296.88  ,   8619.81  ,
        21474.    ,   8325.98  ,   3720.67  ,   8138.38  ,   5176.48  ,
        10912.61  ,  23010.35  ,   7152.06  ,   3630.95  ,   6057.84  ,
         5397.29  ,  11208.02  ,  19713.71  ,   7590.84  ,   4660.46  ,
         4677.07  ,   5656.24  ,   9628.46  ,  16920.52  ,   8494.75  ,
         2694.02  ,   5062.85  ,   7513.31  ,  12618.85  ,  22528.09  ,
         5423.18  ,   2772.88  ,   7432.26  ,   4476.8   ,  10645.83  ,
        17208.59  ,   4876.47  ,   5488.3   , 165500.    ,   8372.6   ,
         9391.06  ,  20095.34  ,   5018.79  ,   3541.71  ,   5604.21  ,
         7627.29  ,  10345.07  ,  20781.86  ,   9191.78  ,   4956.52  ,
         6628.79  ,   8580.24  ,   8001.08  ,  22481.24  ,   6570.94  ,
         3676.18  ,   5211.38  ,   7596.38  ,  11837.68  ,  25382.07  ,
         8346.45  ,   4395.53  ,   6076.47  ,   8840.63  ,  10989.    ,
        19868.63  ,   6420.65  ,   3210.51  ,   6397.38  ,   6378.04  ,
         7817.24  ,  13946.71  ,   8333.37  ,   3937.52  ,   6658.72  ,
         6955.51  ,   6630.92  ,  17282.36  ,   7887.26  ,   4301.17  ,
         8072.73  ,   7363.06  ,   6655.61  ,  23491.84  ,   7250.66  ,
         3187.31  ,   5093.94  ,   6328.07  ,   7885.55  ,  22791.81  ,
         6894.61  ,   3881.04  ,   5331.34  ,   5998.8   ,   7909.9   ,
        18730.26  ,   7134.03  ,   4691.62  ,   7635.28  ,   5341.62  ,
        12464.5   ,  25515.81  ,   5711.14  ,   3851.94  ,   8629.51  ,
         5804.15  ,  10314.47  ,  22156.67  ,   7099.56  ,   3931.5   ,
         5986.61  ,   8792.75  ,   6982.51  ,  14606.07  ,   8036.99  ,
         3046.73  ,   6732.63  ,   7811.21  ,  10329.68  ,  19697.9   ,
         9603.17  ,   2559.88  ,   7398.09  ,   5208.38  ,   8258.97  ,
        14898.09  ,   5998.22  ,   2829.78  ,   5284.71  ,   5949.68  ,
        12247.66  ,  18428.52  ,   7120.2   ,   5035.07  ,   7101.    ,
         5818.67  ,  11411.11  ,  16589.35  ,   6257.38  ,   2824.12  ,
         6967.23  ,   8308.31  ,  10903.59  ,  16036.65  ,  10886.86  ,
         4239.57  ,   6731.09  ,   5740.87  ,   8351.77  ,  23786.85  ,
         5131.95  ,   3078.54  ,   5582.12  ,   6688.88  ,   8872.15  ,
        20389.63  ,   9238.99  ,   5325.21  ,   6075.49  ,   5967.    ,
        10035.75  ,  25527.49  ,   8144.38  ,   2747.37  ,   5531.25  ,
         7295.15  ,  11451.08  ,  16939.    ,   9223.5   ,   4297.25  ,
         5210.7   ,   5775.9   ,   7620.99  ,  12326.55  ,   9586.44  ,
         4619.37  ,   5718.27  ,   5830.49  ,   9406.82  ,  21495.24  ,
         5124.44  ,   4271.99  ,   5549.1   ,   5505.12  ,  11204.62  ,
        13383.16  ,   5762.73  ,   3550.6   ,   7467.12  ])

array(['Logiciels', 'Prestations externes', 'Salaires', 'Matériel',
       'Déplacements', 'Logiciel', 'Énergie'], dtype=object)

In [19]:
colonnes_avec_valeurs_espaces = []

for col in df.columns:
    if df[col].astype(str).str.contains(" ", na=False).any():
        colonnes_avec_valeurs_espaces.append(col)

display(colonnes_avec_valeurs_espaces)

['Business_Unit', 'Centre_Cout', 'Nature_Depense']

In [22]:
#Espace inutile

for col in ["Business_Unit", "Centre_Cout","Nature_Depense",]:
    print(f"\n--- {col} ---")
    
    valeurs_avec_espaces = df[col].astype(str)[
        df[col].astype(str).str.strip() != df[col].astype(str)
    ]
    
    display(valeurs_avec_espaces.unique())

--- Business_Unit ---

array(['Construction France '], dtype=object)

--- Centre_Cout ---

array(['IT '], dtype=object)

--- Nature_Depense ---

array([], dtype=object)

In [25]:
#Majuscules/minuscules
for col in ["Business_Unit", "Centre_Cout", "Nature_Depense"]:
    print(f"\n--- {col} ---")
    
    display(
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
        .value_counts()
    )

--- Business_Unit ---

Business_Unit
construction france    216
construction uk        216
energie                216
infrastructures        216
Name: count, dtype: int64

--- Centre_Cout ---

Centre_Cout
it                     289
finance                288
ressources humaines    144
maintenance            143
Name: count, dtype: int64

--- Nature_Depense ---

Nature_Depense
logiciels               144
prestations externes    144
salaires                144
matériel                144
déplacements            144
énergie                 143
logiciel                  1
Name: count, dtype: int64

In [29]:
#Montant suspect
display(df["Budget_EUR"].describe())
display(df["Reel_EUR"].describe())

count       863.000000
mean       8833.984415
std        7001.697883
min        2639.600000
25%        5458.435000
50%        7275.480000
75%        9332.485000
max      150000.000000
Name: Budget_EUR, dtype: float64

count       864.000000
mean       8994.577964
std        7458.067723
min        -500.000000
25%        5463.912500
50%        7284.660000
75%       10018.110000
max      165500.000000
Name: Reel_EUR, dtype: float64

In [32]:
#plus gros montant(Budget_EUR)

display(df.nlargest(10, "Budget_EUR"))

#plus gros montant(Reel_EUR)
display(df.nlargest(10, "Reel_EUR"))

,Mois,Business_Unit_Code,Business_Unit,Centre_Cout_Code,Centre_Cout,Nature_Depense,Budget_EUR,Reel_EUR
713,2025-10,BU04,Infrastructures,CC4002,Maintenance,Énergie,150000.00,165500.00
266,2025-04,BU03,Energie,CC3003,Finance,Salaires,24263.68,25071.48
674,2025-10,BU02,Construction UK,CC2002,Ressources Humaines,Salaires,24166.62,20861.49
614,2025-09,BU03,Energie,CC3001,IT,Salaires,24126.96,23766.99
662,2025-10,BU01,Construction France,CC1003,Finance,Salaires,24039.34,23106.03
590,2025-09,BU01,Construction France,CC1003,Finance,Salaires,23900.31,23011.65
206,2025-03,BU04,Infrastructures,CC4002,Maintenance,Salaires,23766.56,24699.03
254,2025-04,BU03,Energie,CC3001,IT,Salaires,23757.84,25883.87
542,2025-08,BU03,Energie,CC3001,IT,Salaires,23703.11,23803.67
512,2025-08,BU01,Construction France,CC1002,Ressources Humaines,Salaires,23698.08,23851.89

,Mois,Business_Unit_Code,Business_Unit,Centre_Cout_Code,Centre_Cout,Nature_Depense,Budget_EUR,Reel_EUR
713,2025-10,BU04,Infrastructures,CC4002,Maintenance,Énergie,150000.00,165500.00
26,2025-01,BU02,Construction UK,CC2002,Ressources Humaines,Salaires,23646.59,27082.27
560,2025-08,BU04,Infrastructures,CC4001,IT,Salaires,23098.48,26918.16
434,2025-07,BU01,Construction France,CC1001,IT,Salaires,22807.28,26507.04
56,2025-01,BU04,Infrastructures,CC4001,IT,Salaires,23540.73,26287.46
254,2025-04,BU03,Energie,CC3001,IT,Salaires,23757.84,25883.87
836,2025-12,BU03,Energie,CC3002,Maintenance,Salaires,22875.01,25527.49
776,2025-11,BU04,Infrastructures,CC4001,IT,Salaires,22347.24,25515.81
128,2025-02,BU04,Infrastructures,CC4001,IT,Salaires,23610.47,25491.99
734,2025-11,BU01,Construction France,CC1003,Finance,Salaires,22904.14,25382.07

In [38]:
#Valeur extreme(Budget_EUR)

Q1 = df["Budget_EUR"].quantile(0.25)
Q3 = df["Budget_EUR"].quantile(0.75)

IQR = Q3 - Q1

borne_basse = Q1 - 1.5 * IQR
borne_haute = Q3 + 1.5 * IQR

suspects_budget = df[
    (df["Budget_EUR"] < borne_basse) |
    (df["Budget_EUR"] > borne_haute)
]

display(suspects_budget)

,Mois,Business_Unit_Code,Business_Unit,Centre_Cout_Code,Centre_Cout,Nature_Depense,Budget_EUR,Reel_EUR
2,2025-01,BU01,Construction France,CC1001,IT,Salaires,15185.00,13688.95
8,2025-01,BU01,Construction France,CC1002,Ressources Humaines,Salaires,16785.82,17174.74
14,2025-01,BU01,Construction France,CC1003,Finance,Salaires,19898.08,17218.38
26,2025-01,BU02,Construction UK,CC2002,Ressources Humaines,Salaires,23646.59,27082.27
32,2025-01,BU02,Construction UK,CC2003,Finance,Salaires,16534.09,17015.06
...,...,...,...,...,...,...,...,...
818,2025-12,BU02,Construction UK,CC2002,Ressources Humaines,Salaires,17812.61,16036.65
824,2025-12,BU02,Construction UK,CC2003,Finance,Salaires,21945.90,23786.85
830,2025-12,BU03,Energie,CC3001,IT,Salaires,19986.42,20389.63
836,2025-12,BU03,Energie,CC3002,Maintenance,Salaires,22875.01,25527.49
854,2025-12,BU04,Infrastructures,CC4002,Maintenance,Salaires,20191.55,21495.24

In [39]:
#Valeur extreme (reel_EUR)

Q1 = df["Reel_EUR"].quantile(0.25)
Q3 = df["Reel_EUR"].quantile(0.75)

IQR = Q3 - Q1

borne_basse = Q1 - 1.5 * IQR
borne_haute = Q3 + 1.5 * IQR

suspects_reel = df[
    (df["Reel_EUR"] < borne_basse) |
    (df["Reel_EUR"] > borne_haute)
]

display(suspects_reel)

,Mois,Business_Unit_Code,Business_Unit,Centre_Cout_Code,Centre_Cout,Nature_Depense,Budget_EUR,Reel_EUR
8,2025-01,BU01,Construction France,CC1002,Ressources Humaines,Salaires,16785.82,17174.74
14,2025-01,BU01,Construction France,CC1003,Finance,Salaires,19898.08,17218.38
26,2025-01,BU02,Construction UK,CC2002,Ressources Humaines,Salaires,23646.59,27082.27
32,2025-01,BU02,Construction UK,CC2003,Finance,Salaires,16534.09,17015.06
38,2025-01,BU03,Energie,CC3001,IT,Salaires,21829.72,19088.67
...,...,...,...,...,...,...,...,...
824,2025-12,BU02,Construction UK,CC2003,Finance,Salaires,21945.90,23786.85
830,2025-12,BU03,Energie,CC3001,IT,Salaires,19986.42,20389.63
836,2025-12,BU03,Energie,CC3002,Maintenance,Salaires,22875.01,25527.49
842,2025-12,BU03,Energie,CC3003,Finance,Salaires,14931.27,16939.00
854,2025-12,BU04,Infrastructures,CC4002,Maintenance,Salaires,20191.55,21495.24

In [40]:
#Nombre de business unit

nombre_business_units = df["Business_Unit"].nunique()

display("Nombre de Business Units :", nombre_business_units)

'Nombre de Business Units :'

5

In [41]:
display(df["Business_Unit"].unique())

array(['Construction France', 'Construction France ', 'Construction UK',
       'Energie', 'Infrastructures'], dtype=object)

In [44]:
nombre_centres_cout = df["Centre_Cout"].nunique()

display("Nombre de centres de coût :", nombre_centres_cout)

display(df["Centre_Cout"].unique())

'Nombre de centres de coût :'

5

array(['IT', 'Ressources Humaines', 'Finance', 'Maintenance', 'IT '],
      dtype=object)

In [4]:
display(df[df["Reel_EUR"] < 0])

,Mois,Business_Unit_Code,Business_Unit,Centre_Cout_Code,Centre_Cout,Nature_Depense,Budget_EUR,Reel_EUR
47,2025-01,BU03,Energie,CC3002,Maintenance,Énergie,7275.48,-500.0

**Nettoyage**

In [6]:
#Valeur manquante

display(df[df["Budget_EUR"].isna()])

,Mois,Business_Unit_Code,Business_Unit,Centre_Cout_Code,Centre_Cout,Nature_Depense,Budget_EUR,Reel_EUR
29,2025-01,BU02,Construction UK,CC2002,Ressources Humaines,Énergie,NaN,4463.99

In [7]:
#remplace la valeur manquante
df.loc[29,"Budget_EUR"] = 42500

display(df.loc[29])

Mois                              2025-01
Business_Unit_Code                   BU02
Business_Unit             Construction UK
Centre_Cout_Code                   CC2002
Centre_Cout           Ressources Humaines
Nature_Depense                    Énergie
Budget_EUR                        42500.0
Reel_EUR                          4463.99
Name: 29, dtype: object

In [10]:
#Format de donnée
display(df["Mois"].unique())

array(['2025-01', '2025-02', '2025/08', '2025-03', '2025-04', '2025-05',
       '2025-06', '2025-07', '2025-08', '2025-09', '2025-10', '2025-11',
       '2025-12'], dtype=object)

In [18]:
#uniformiser le format date
df["Mois"] = df["Mois"].astype(str).str.replace("/","-",regex=False)

df["Mois_date"] = pd.to_datetime(
    df["Mois"],
    format="%Y-%m",
    errors="coerce"
)

display(df["Mois_date"].dt.strftime("%Y-%m").unique())

array(['2025-01', '2025-02', '2025-08', '2025-03', '2025-04', '2025-05',
       '2025-06', '2025-07', '2025-09', '2025-10', '2025-11', '2025-12'],
      dtype=object)

In [19]:
#Supprimer les espaces inutiles
colonnes_libelles = [
    "Business_Unit",
    "Centre_Cout",
    "Nature_Depense"
]

for col in colonnes_libelles:
    df[col] = df[col].astype("string").str.strip()

In [20]:
for col in colonnes_libelles:
    print(f"\n{col}")
    display(df[col].unique())

Business_Unit

<StringArray>
['Construction France', 'Construction UK', 'Energie', 'Infrastructures']
Length: 4, dtype: string

Centre_Cout

<StringArray>
['IT', 'Ressources Humaines', 'Finance', 'Maintenance']
Length: 4, dtype: string

Nature_Depense

<StringArray>
[           'Logiciels', 'Prestations externes',             'Salaires',
             'Matériel',         'Déplacements',             'Logiciel',
              'Énergie']
Length: 7, dtype: string

In [22]:
#Uniformiser les majuscules/minuscule
for col in colonnes_libelles:
    df[col] = df[col].str.strip().str.upper()

In [23]:
for col in colonnes_libelles:
    print(f"\n--- {col} ---")
    display(df[col].value_counts())

--- Business_Unit ---

Business_Unit
CONSTRUCTION FRANCE    216
CONSTRUCTION UK        216
ENERGIE                216
INFRASTRUCTURES        216
Name: count, dtype: Int64

--- Centre_Cout ---

Centre_Cout
IT                     289
FINANCE                288
RESSOURCES HUMAINES    144
MAINTENANCE            143
Name: count, dtype: Int64

--- Nature_Depense ---

Nature_Depense
LOGICIELS               144
PRESTATIONS EXTERNES    144
SALAIRES                144
MATÉRIEL                144
DÉPLACEMENTS            144
ÉNERGIE                 143
LOGICIEL                  1
Name: count, dtype: Int64

In [24]:
#exporter le fichier nettoyer
df.to_excel("sap_co_budget_reel_raw_cleaned.xlsx", index=False)

display("Fichier Excel créé avec succè !")

'Fichier Excel créé avec succè !'